### ISSUE TITLE
Graphs with mostDeviant

### ISSUE THREAD

**Issue by blkperl** [PrFalken/leonardo#6]
I'm trying to figure out how to make a graph with mostDeviant,  As described here: http://obfuscurity.com/2012/04/Unhelpful-Graphite-Tip-6

The following renders the graph but doesn't display the hostnames of the 5 lines and instead labels them as mostDeviant.

``` yaml
fields:
    mostDeviant:
        color: green
        field_linewidth: 2
        data: mostDeviant(5, collectd.*.load.load.shortterm)
```
